import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Sora, Space_Grotesk, Lato } from 'next/font/google'
import "./globals.css";

const spg = Space_Grotesk({
  subsets: ['latin'], 
  weight: ['400', '600', '700'],
  variable: '--font-space-grotesk',
})

const lato = Lato({
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-lato',
})
const sora = Sora({ 
  subsets: ['latin'], 
  weight: ['400', '600', '700'],
  variable: '--font-sora', 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
